name: Build Crate

on:
  workflow_call:
    inputs:
      rust:
        type: string
  workflow_dispatch:
    inputs:
      rust:
        description: Rust version
        default: 1.75.0
        required: true
        type: string

env:
  CACHE: true

jobs:
  build:
    name: Build
    runs-on: buildjet-8vcpu-ubuntu-2204
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Load environment variables
        run: cat .github/.env >> $GITHUB_ENV

      - name: Install Rust
        uses: nifty-oss/actions/install-rust@v1
        with:
          toolchain: ${{ inputs.rust || env.RUST_VERSION }}

      - name: Cache build dependencies
        uses: nifty-oss/actions/buildjet-cache-crate@v1
        with:
          folder: '.'
          key: crate-build

      - name: Run cargo fmt
        uses: nifty-oss/actions/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy
        uses: nifty-oss/actions/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features --no-deps

      - name: Build Rust client
        shell: bash
        run: cargo build --all-features --release
