name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CACHE: true

jobs:
  changes:
    name: Detect changes
    runs-on: buildjet-8vcpu-ubuntu-2204
    outputs:
      crate: ${{ steps.changes.outputs.crate }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Load environment variables
        run: cat .github/.env >> $GITHUB_ENV

      - name: Detect changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: .github/file-filters.yml

  build:
    name: Crate
    if: ${{ needs.changes.outputs.crate == 'true' }}
    needs: changes
    uses: ./.github/workflows/build.yml
    secrets: inherit

  test:
    name: Crate
    if: ${{ needs.changes.outputs.crate == 'true' }}
    needs: changes
    uses: ./.github/workflows/test.yml
    secrets: inherit
