name: Main

on:
  push:
    branches: [main]
  pull_request:

env:
  CACHE: true

jobs:
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          cargo-cache-key: cargo-spellcheck
          components: spellcheck

      - name: cargo-spellcheck
        run: ./make spellcheck

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          cargo-cache-key: cargo-lint
          toolchain: format, lint
          components: hack, miri

      - name: cargo-clippy
        run: ./make clippy

      - name: cargo-fmt
        run: ./make format

      - name: cargo-doc
        run: ./make doc

      - name: cargo-hack
        run: ./make hack

      - name: cargo-miri
        run: ./make miri

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          cargo-cache-key: cargo-build
          toolchain: build
          solana: true

      - name: cargo-build
        run: ./make build

      - name: cargo-build-sbf
        run: ./make build-sbf

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          cargo-cache-key: cargo-test
          toolchain: test
          solana: true

      - name: cargo-test
        run: ./make test
