name: Test Crate

on:
  workflow_call:
    inputs:
      rust:
        type: string
  workflow_dispatch:
    inputs:
      rust:
        description: Rust version
        default: 1.75.0
        required: true
        type: string

env:
  CACHE: true

jobs:
  test:
    name: Test
    runs-on: buildjet-8vcpu-ubuntu-2204
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Load environment variables
        run: cat .github/.env >> $GITHUB_ENV

      - name: Install Rust
        uses: nifty-oss/actions/install-rust@v1
        with:
          toolchain: ${{ inputs.rust || env.RUST_VERSION }}

      - name: Cache build dependencies
        uses: nifty-oss/actions/buildjet-cache-crate@v1
        with:
          folder: '.'
          key: crate-test

      - name: Run tests
        shell: bash
        run: cargo test
